# Generated by Django 5.0.6 on 2024-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_customer_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicsetup',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='level_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='level_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='level_3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='level_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='level_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='product_barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bicsetup',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bicsetup',
            name='product_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bicsetup',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
